// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krqowiptyqkxuzenorlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtycW93aXB0eXFreHV6ZW5vcmx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MTQ5MDQsImV4cCI6MjA2MzQ5MDkwNH0.9rtddIFY7FX1c2eR-VuvagiFGDURpi5PbuxVYvvwuIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);